"""
Dashboard Renderer
Formats scored job results into a clean Markdown dashboard organized by status.
Also maintains a persistent JSON log of all jobs seen.
"""

import json
from datetime import datetime
from pathlib import Path

LOG_PATH = Path(__file__).parent.parent / "data" / "jobs_log.json"
LOG_PATH.parent.mkdir(exist_ok=True)


def render_dashboard(scored_jobs: list[dict], sync_time: str = None) -> str:
    """
    Renders scored jobs into a Markdown dashboard organized by lifecycle status.
    """
    if not sync_time:
        sync_time = datetime.now().strftime("%Y-%m-%d %H:%M")

    lines = [
        f"# 🗂️ Deepam's Career Ops Dashboard",
        f"**Last Synced:** {sync_time}  |  **Records Found:** {len(scored_jobs)}",
        "",
        "---",
        "",
    ]

    # Define the order of sections based on status
    status_order = [
        ("ACCEPTED 🏆", "ACCEPTED"),
        ("IN PROGRESS 👀", "IN_PROGRESS"),
        ("APPLIED ✅", "APPLIED"),
        ("NEW ALERTS 🔔", "ALERT"),
        ("REJECTED ❌", "REJECTED")
    ]

    for section_title, status_key in status_order:
        # Filter jobs for this specific category (Case-insensitive check)
        category_jobs = [j for j in scored_jobs if str(j.get("status", "")).upper() == status_key]
        
        if not category_jobs:
            continue

        lines.append(f"## {section_title}")
        lines.append("")
        lines.append("| Rating | Score | Job Title | Company | Verdict |")
        lines.append("|:---:|:---:|:---|:---|:---|")

        for job in category_jobs:
            emoji = job.get("emoji", "⚪")
            score = job.get("match_score", 0)
            title = job.get("title", "Unknown")
            company = job.get("company", "Unknown")
            verdict = job.get("verdict", "—")
            url = job.get("url")

            title_cell = f"[{title}]({url})" if url else title
            lines.append(f"| {emoji} | {score}/100 | **{title_cell}** | {company} | {verdict} |")
        
        lines.append("")

        if status_key in ["ALERT", "IN_PROGRESS", "ACCEPTED"]:
            for job in category_jobs:
                if job.get("match_score", 0) >= 70 or status_key != "ALERT":
                    lines.extend(_render_job_detail(job))
        
        lines.append("---")

    lines.append("*Generated by Career Ops Manager*")
    return "\n".join(lines)


def _render_job_detail(job: dict) -> list[str]:
    lines = []
    title = job.get("title", "Unknown")
    company = job.get("company", "Unknown")
    score = job.get("match_score", 0)
    matches = job.get("top_matches", [])
    gaps = job.get("gaps", [])
    tweak = job.get("resume_tweak")
    message = job.get("recruiter_message")

    lines.append(f"### 🔍 Detail: {title} @ {company}")
    lines.append(f"🎯 Match Score: **{score}/100**")

    if matches:
        lines.append(f"✅ **Matches:** {', '.join(matches)}")
    if gaps:
        lines.append(f"⚠️ **Gaps:** {', '.join(gaps)}")
    if tweak:
        lines.append(f"\n💡 **Resume Tweak:** {tweak}")
    if message:
        lines.append(f"\n📨 **Recruiter Message:**")
        lines.append(f"> {message}")
    lines.append("")
    return lines


def save_to_log(scored_jobs: list[dict]):
    """
    Appends scored jobs to a persistent JSON log file.
    Avoids duplicates by job title + company + status.
    """
    raw_data = []
    if LOG_PATH.exists():
        with open(LOG_PATH) as f:
            try:
                raw_data = json.load(f)
            except json.JSONDecodeError:
                raw_data = []

    # FIX: Extract the list of jobs regardless of whether the file is a List or Dict
    if isinstance(raw_data, dict) and 'jobs' in raw_data:
        existing_jobs = raw_data['jobs']
    else:
        existing_jobs = raw_data if isinstance(raw_data, list) else []

    # FIX: Ensure we only run .get() on actual dictionaries to avoid AttributeError
    existing_keys = {
        (j.get("title"), j.get("company"), str(j.get("status", "")).upper()) 
        for j in existing_jobs 
        if isinstance(j, dict)
    }
    
    new_entries = []
    for j in scored_jobs:
        # Standardize the incoming status to uppercase
        j_status = str(j.get("status", "ALERT")).upper()
        j["status"] = j_status 
        
        key = (j.get("title"), j.get("company"), j_status)
        if key not in existing_keys:
            new_entries.append(j)

    if new_entries:
        existing_jobs.extend(new_entries)
        
        # Save back in the format the Streamlit app prefers
        final_output = {"jobs": existing_jobs}
        
        with open(LOG_PATH, "w") as f:
            json.dump(final_output, f, indent=2)
        print(f"💾 Saved {len(new_entries)} new job(s)/updates to log.")
    else:
        print("ℹ️ No new jobs or status updates to save.")


def load_log() -> list[dict]:
    """Loads all previously seen jobs from the log."""
    if not LOG_PATH.exists():
        return []
    with open(LOG_PATH) as f:
        try:
            raw_data = json.load(f)
            # Standardize output to always return a list
            if isinstance(raw_data, dict) and 'jobs' in raw_data:
                return raw_data['jobs']
            return raw_data if isinstance(raw_data, list) else []
        except json.JSONDecodeError:
            return []