"""
Dashboard Renderer
Formats scored job results into a clean Markdown dashboard organized by status.
Also maintains a persistent JSON log of all jobs seen.
"""

import json
from datetime import datetime
from pathlib import Path

LOG_PATH = Path(__file__).parent.parent / "data" / "jobs_log.json"
LOG_PATH.parent.mkdir(exist_ok=True)


def render_dashboard(scored_jobs: list[dict], sync_time: str = None) -> str:
    """
    Renders scored jobs into a Markdown dashboard organized by lifecycle status.
    """
    if not sync_time:
        sync_time = datetime.now().strftime("%Y-%m-%d %H:%M")

    lines = [
        f"# 🗂️ Saloni's Career Ops Dashboard",
        f"**Last Synced:** {sync_time}  |  **Records Found:** {len(scored_jobs)}",
        "",
        "---",
        "",
    ]

    # Define the order of sections based on status
    status_order = [
        ("ACCEPTED 🏆", "ACCEPTED"),
        ("IN PROGRESS 👀", "IN_PROGRESS"),
        ("APPLIED ✅", "APPLIED"),
        ("NEW ALERTS 🔔", "ALERT"),
        ("REJECTED ❌", "REJECTED")
    ]

    for section_title, status_key in status_order:
        # Filter jobs for this specific category
        category_jobs = [j for j in scored_jobs if j.get("status") == status_key]
        
        if not category_jobs:
            continue

        lines.append(f"## {section_title}")
        lines.append("")
        lines.append("| Rating | Score | Job Title | Company | Verdict |")
        lines.append("|:---:|:---:|:---|:---|:---|")

        for job in category_jobs:
            emoji = job.get("emoji", "⚪")
            score = job.get("match_score", 0)
            title = job.get("title", "Unknown")
            company = job.get("company", "Unknown")
            verdict = job.get("verdict", "—")
            url = job.get("url")

            title_cell = f"[{title}]({url})" if url else title
            lines.append(f"| {emoji} | {score}/100 | **{title_cell}** | {company} | {verdict} |")
        
        lines.append("")

        # Add detailed breakdowns for high-interest categories
        if status_key in ["ALERT", "IN_PROGRESS", "ACCEPTED"]:
            for job in category_jobs:
                # Only show details for jobs that have a high match score or are in progress
                if job.get("match_score", 0) >= 70 or status_key != "ALERT":
                    lines.extend(_render_job_detail(job))
        
        lines.append("---")

    lines.append("*Generated by Career Ops Manager*")
    return "\n".join(lines)


def _render_job_detail(job: dict) -> list[str]:
    lines = []
    title = job.get("title", "Unknown")
    company = job.get("company", "Unknown")
    score = job.get("match_score", 0)
    matches = job.get("top_matches", [])
    gaps = job.get("gaps", [])
    tweak = job.get("resume_tweak")
    message = job.get("recruiter_message")

    lines.append(f"### 🔍 Detail: {title} @ {company}")
    lines.append(f"🎯 Match Score: **{score}/100**")

    if matches:
        lines.append(f"✅ **Matches:** {', '.join(matches)}")
    if gaps:
        lines.append(f"⚠️ **Gaps:** {', '.join(gaps)}")
    if tweak:
        lines.append(f"\n💡 **Resume Tweak:** {tweak}")
    if message:
        lines.append(f"\n📨 **Recruiter Message:**")
        lines.append(f"> {message}")
    lines.append("")
    return lines


def save_to_log(scored_jobs: list[dict]):
    """
    Appends scored jobs to a persistent JSON log file.
    Avoids duplicates by job title + company + status.
    """
    existing = []
    if LOG_PATH.exists():
        with open(LOG_PATH) as f:
            try:
                existing = json.load(f)
            except json.JSONDecodeError:
                existing = []

    # Include 'status' in the key so moving from 'Applied' to 'Rejected' updates the log
    existing_keys = {(j.get("title"), j.get("company"), j.get("status")) for j in existing}
    
    new_jobs = [
        j for j in scored_jobs 
        if (j.get("title"), j.get("company"), j.get("status")) not in existing_keys
    ]

    if new_jobs:
        existing.extend(new_jobs)
        with open(LOG_PATH, "w") as f:
            json.dump(existing, f, indent=2)
        print(f"💾 Saved {len(new_jobs)} new job(s)/updates to log.")
    else:
        print("ℹ️ No new jobs or status updates to save.")


def load_log() -> list[dict]:
    """Loads all previously seen jobs from the log."""
    if not LOG_PATH.exists():
        return []
    with open(LOG_PATH) as f:
        try:
            return json.load(f)
        except json.JSONDecodeError:
            return []